
services:
  backend:
    build:
      context: ./backend
    container_name: backend_desafio
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/desafio
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db
#      - rabbitmq
#    command: ["./wait-for-it.sh", "db:5432", "java", "-jar", "backend.jar"]

  frontend:
    build: ./frontend
    container_name: frontend_desafio
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080

  db:
    image: postgres:13-alpine
    container_name: db
    environment:
      POSTGRES_DB: desafio
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

#  rabbitmq:
#    image: rabbitmq:management
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
